[project]
name = "beautiful-soup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fixalot", email = "35915923+fix-a-lot@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "apscheduler>=3.11.3",
    "bs4>=0.0.2",
    "lxml>=6.1.2",
    "requests>=2.34.2",
]

[project.scripts]
main = "beautiful_soup:main"
sub1 = "bs_with_request1.main:main"
sub2 = "bs_with_request2.main:main"
sub3 = "crawler1.main:main"
sub4 = "crawler2.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

